# Generated by Django 4.1.5 on 2023-01-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('caption', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('caption', models.CharField(max_length=64)),
                ('brief', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('preview', models.ImageField(blank=True, upload_to='')),
                ('visible', models.BooleanField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventureapp.country')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventureapp.myyear')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.IntegerField()),
                ('txt1', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('txt2', models.TextField(blank=True)),
                ('txt_url', models.TextField(blank=True)),
                ('ref_url', models.URLField(blank=True)),
                ('visible', models.BooleanField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventureapp.history')),
            ],
        ),
    ]
